// Generated by tools/re/generate_ce_contracts.py; do not edit.
// Offline identity evidence is not title admission or headset acceptance.
#pragma once
#include <cstdint>
namespace halo_ce::contract {
struct Entry { const char* name; uint32_t rva; const char* pattern; bool unwind; };
struct Witness { uint32_t rva; const char* pattern; };
struct Relative { uint32_t rva, size, displacement, target; };
struct Pointer { uint32_t rva, target; };
inline constexpr uint32_t imageSize=0x3D82000;
inline constexpr uint32_t timestamp=0x68A0E4CF;
inline constexpr Entry entries[]={
    {"native_player_window",0xbbca64,"48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 41 54 41 55 41 56 41 57 48 8D A8 48 FB FF FF 48 81 EC 90 05 00 00",true},
    {"native_frustum",0xb8f690,"48 8B C4 55 53 56 57 41 54 41 56 41 57 48 8D 68 A1 48 81 EC F0 00 00 00 44 0F BF 51 32",true},
    {"native_camera_build",0xac450c,"48 8B C4 48 89 58 08 48 89 70 10 48 89 78 18 4C 89 70 20 55 48 8D 68 A1 48 81 EC 90 00 00 00 48 8B FA 48 8B D9 48 85 D2 0F 84 46 01 00 00 F2",true},
    {"native_window_loop",0xbbce28,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 18 48 89 78 20 41 56 48 83 EC 30 F3 0F 10 44 24 68 41 BE 01 00 00 00",true},
    {"native_game_render",0xac47c0,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 20 57 41 54 41 55 41 56 41 57 48 83 EC 60",true},
    {"initialized_clock_render_gate",0xac269c,"40 53 48 83 EC 30 48 8B 05 BF D6 3D 02 ?? ?? ?? ??",true},
    {"anniversary_camera_view_rebuild",0x11aba0,"48 8B C4 48 89 58 10 48 89 70 18 55 57 41 56 48 8D 68 A1 48 81 EC 00 01 00 00 0F 29 70 D8 0F 29 78 C8 44 0F 29 40 B8 44 0F 29 48 A8",true},
    {"anniversary_camera_projection_rebuild",0x11ae90,"40 53 48 83 EC 50 F3 0F 10 81 4C 01 00 00 48 8B D9 F3 0F 59 05 73 49 83 01",true},
    {"anniversary_camera_culling_rebuild",0x11e5f0,"48 8B C4 48 89 58 10 48 89 70 18 48 89 78 20 55 48 8D A8 38 FF FF FF 48 81 EC C0 01 00 00",true},
    {"anniversary_view_append",0x2ea720,"48 8B C4 48 89 58 18 55 56 57 41 54 41 55 41 56 41 57 48 8D A8 78 FC FF FF",true},
    {"anniversary_primary_view_pair_builder",0x4547e0,"48 8B C4 48 89 58 08 48 89 68 10 48 89 70 18 57 41 54 41 55 41 56 41 57 48 81 EC D0 00 00 00 8B 0D 93 33 6C 02",true},
    {"anniversary_view_prepare",0x455170,"4C 8B DC 53 56 41 56 48 81 EC 90 00 00 00 48 8B 05 8B FE 71 01 48 33 C4",true},
    {"anniversary_per_view_output",0x45e2b0,"48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 60 80 3D 4E CE 71 01 00 8B D9",true},
    {"anniversary_full_frame_not_replayable",0x455a10,"48 8B C4 55 41 54 41 55 41 56 41 57 48 8D A8 88 F3 FF FF 48 81 EC 50 0D 00 00",true},
    {"anniversary_backend_constructor",0x203580,"48 89 4C 24 08 56 57 41 56 48 83 EC 40 48 C7 44 24 30 FE FF FF FF 48 89 5C 24 68 48 89 6C 24 70 41 0F B6 F1 49 8B E8 48",true},
    {"anniversary_surface_transfer",0x204c40,"40 55 56 57 41 54 41 55 41 56 41 57 48 81 EC 90 00 00 00 48 C7 44 24 50 FE FF FF FF 48 89 9C 24 E0 00 00 00 48 8B 05 A5",true},
    {"anniversary_surface_selector",0xad5f0,"4C 8B 91 A8 00 00 00 4C 8B C1 4D 85 D2 74 45 48 8B 05 B2 D0 B3 01 44 8B",false},
    {"anniversary_legacy_mode_reader",0x84730,"48 8B C4 48 89 48 08 57 48 83 EC 40 48 C7 40 E0 FE FF FF FF 48 89 58 10 49 8B D9 48 8B F9 C7 40 DC 00 00 00 00 83 3D 28",true},
    {"anniversary_preparation_complete_not_wait",0x4556b0,"48 89 5C 24 08 57 48 83 EC 20 4C 8D 41 70 48 8B F9 E8 9A B9 E8 FF 45 33 C0 48 8D 57 70",true},
};
inline constexpr Witness witnesses[]={
    {0xbbccad,"E8 ?? ?? ?? ??"},
    {0xbbcee6,"E8 ?? ?? ?? ??"},
    {0xac483f,"48 8D 15 ?? ?? ?? ??"},
    {0xac48e0,"E8 ?? ?? ?? ??"},
    {0xac4942,"E8 ?? ?? ?? ??"},
    {0xac4956,"E8 ?? ?? ?? ??"},
    {0xac26a2,"48 8B 05 ?? ?? ?? ??"},
    {0xac2704,"E8 ?? ?? ?? ??"},
    {0x2eab31,"48 69 C9 C8 03 00 00"},
    {0x2eab9d,"44 89 6C 39 1C"},
    {0x2eabb2,"48 8D 4A 40"},
    {0x2ea8b3,"E8 ?? ?? ?? ??"},
    {0x2ea96d,"E8 ?? ?? ?? ??"},
    {0x454a95,"45 84 E4"},
    {0x454aa7,"83 0E 01"},
    {0x454aaa,"41 B8 0B 02 00 00"},
    {0x454ab0,"83 B8 38 02 00 00 00"},
    {0x454a69,"E8 ?? ?? ?? ??"},
    {0x454c93,"E8 ?? ?? ?? ??"},
    {0x45518d,"83 B9 58 BE 00 00 00"},
    {0x455273,"49 8D 56 70"},
    {0x455277,"48 81 C1 B0 00 00 00"},
    {0x45527e,"41 B8 E8 BD 00 00"},
    {0x45560d,"49 8D 56 70"},
    {0x455308,"E8 ?? ?? ?? ??"},
    {0x455611,"E8 ?? ?? ?? ??"},
    {0x455373,"E8 ?? ?? ?? ??"},
    {0x455506,"E8 ?? ?? ?? ??"},
    {0x45526c,"48 8B 0D ?? ?? ?? ??"},
    {0x455284,"E8 ?? ?? ?? ??"},
    {0x455267,"E8 ?? ?? ?? ??"},
    {0x45e2de,"BA 01 00 00 04"},
    {0x45e34c,"89 74 24 44"},
    {0x45e35d,"89 44 24 44"},
    {0x45e370,"FF 90 90 01 00 00"},
    {0x45e434,"C7 05 DE CC 71 01 FF FF FF FF"},
    {0x45e2ce,"E8 ?? ?? ?? ??"},
    {0x456f18,"B8 FF FF FF FF"},
    {0x456f1d,"F0 0F C1 05 3F FC 75 01"},
    {0x456dd0,"E8 ?? ?? ?? ??"},
    {0x203643,"48 8D 05 C6 66 5F 01"},
    {0x20364a,"48 89 03"},
    {0x203660,"48 89 AB E0 0C 00 00"},
    {0x204c7c,"4C 8B 22"},
    {0x204c7f,"4C 8B 6A 08"},
    {0x204d2b,"48 8B A8 70 01 00 00"},
    {0x204d4b,"4C 8B 98 E0 00 00 00"},
    {0x204d94,"48 8B 90 E0 00 00 00"},
    {0x204d46,"E8 ?? ?? ?? ??"},
    {0x204d69,"E8 ?? ?? ?? ??"},
    {0x204db6,"E8 ?? ?? ?? ??"},
    {0x204dc5,"E8 ?? ?? ?? ??"},
    {0xad5f0,"4C 8B 91 A8 00 00 00"},
    {0xad61e,"48 8B 8A 18 01 00 00"},
    {0xad63c,"49 8B 80 B0 00 00 00"},
    {0x4556d9,"C7 87 60 BE 00 00 01 00 00 00"},
    {0x4556ed,"48 FF 25 C4 BB 2F 01"},
    {0x4556c1,"E8 ?? ?? ?? ??"},
    {0x4556cd,"E8 ?? ?? ?? ??"},
};
inline constexpr Relative relatives[]={
    {0xbbccad,5,1,0xbbcf30},
    {0xbbcee6,5,1,0xbbca64},
    {0xac483f,7,3,0x2e9fe80},
    {0xac48e0,5,1,0xac450c},
    {0xac4942,5,1,0xac450c},
    {0xac4956,5,1,0xbbce28},
    {0xac26a2,7,3,0x2e9fd68},
    {0xac2704,5,1,0xac47c0},
    {0x2ea8b3,5,1,0x11ae90},
    {0x2ea96d,5,1,0x11e5f0},
    {0x454a69,5,1,0x2ea720},
    {0x454c93,5,1,0x2ea720},
    {0x455308,5,1,0x4547e0},
    {0x455611,5,1,0x4547e0},
    {0x455373,5,1,0x4aa740},
    {0x455506,5,1,0x4aa740},
    {0x45526c,7,3,0x1bea9e0},
    {0x455284,5,1,0x1606fb1},
    {0x455267,5,1,0x4556b0},
    {0x45e2ce,5,1,0x1dc2f0},
    {0x456dd0,5,1,0x45e2b0},
    {0x204d46,5,1,0xad5f0},
    {0x204d69,5,1,0xad5f0},
    {0x204db6,5,1,0xad5f0},
    {0x204dc5,5,1,0xad5f0},
    {0x4556c1,5,1,0x2e1060},
    {0x4556cd,5,1,0x4aa740},
};
inline constexpr Pointer pointers[]={
    {0x17f9ea0,0x204c40},
};
inline constexpr uint32_t native_player_window=0xbbca64;
inline constexpr uint32_t native_frustum=0xb8f690;
inline constexpr uint32_t native_camera_build=0xac450c;
inline constexpr uint32_t native_window_loop=0xbbce28;
inline constexpr uint32_t native_game_render=0xac47c0;
inline constexpr uint32_t initialized_clock_render_gate=0xac269c;
inline constexpr uint32_t anniversary_camera_view_rebuild=0x11aba0;
inline constexpr uint32_t anniversary_camera_projection_rebuild=0x11ae90;
inline constexpr uint32_t anniversary_camera_culling_rebuild=0x11e5f0;
inline constexpr uint32_t anniversary_view_append=0x2ea720;
inline constexpr uint32_t anniversary_primary_view_pair_builder=0x4547e0;
inline constexpr uint32_t anniversary_view_prepare=0x455170;
inline constexpr uint32_t anniversary_per_view_output=0x45e2b0;
inline constexpr uint32_t anniversary_full_frame_not_replayable=0x455a10;
inline constexpr uint32_t anniversary_backend_constructor=0x203580;
inline constexpr uint32_t anniversary_surface_transfer=0x204c40;
inline constexpr uint32_t anniversary_surface_selector=0xad5f0;
inline constexpr uint32_t anniversary_legacy_mode_reader=0x84730;
inline constexpr uint32_t anniversary_preparation_complete_not_wait=0x4556b0;
}
