// Generated by tools/re/verify_ce_hand_alignment.py from official HCEEK tags.
// Model-lateral reflection plane in each verified weapon-root frame.
#pragma once
namespace halo_ce
{
struct HandAlignmentPlane
{
    uint64_t graphIdentity{};uint16_t graphCount{},gunNode{};
    Vec3 normal{};float offset{};
};
inline constexpr HandAlignmentPlane kCeHandAlignmentPlanes[]{
    {0x93663163761AA577ull,42,7,{0.0f,1.0f,0.0f},-9.99999994e-09f}, // assault rifle
    {0xD4E1323E60DB2B87ull,38,17,{0.0f,-6.40120727e-07f,1.0f},0.0f}, // ball
    {0x9D8A310620DE486Dull,38,12,{0.0f,1.0f,0.0f},-0.0f}, // flag
    {0xEC917EC3F1DFFEF9ull,40,7,{0.0f,1.0f,0.0f},0.0f}, // flamethrower
    {0x55EA2D6F6C10C375ull,54,7,{0.00652696469f,0.999920659f,-0.0107738001f},0.0f}, // needler
    {0x24585B0C2FBD0622ull,44,7,{0.0f,1.0f,0.0f},0.0f}, // pistol
    {0x7B974325274A536Dull,41,7,{0.0f,1.0f,0.0f},0.0f}, // plasma pistol
    {0x75A4823A46E33E13ull,42,7,{0.0f,1.0f,0.0f},0.0f}, // plasma rifle
    {0xB0BD3C18EDF619B4ull,41,7,{0.952455007f,0.18348227f,-0.243235928f},0.00468315682f}, // plasma_cannon
    {0xE155408F29C66938ull,42,7,{0.0f,1.0f,0.0f},0.0f}, // rocket launcher
    {0x1D306B5E75713D8Bull,41,7,{0.0f,1.0f,0.0f},0.0f}, // shotgun
    {0x7560F22650441950ull,41,7,{0.0f,1.0f,0.0f},0.0f}, // sniper rifle
};
}
