"""Generate bounded magazine-only VR geometry and per-title identity metadata.

Consumes verified isolated geometry; never includes original tag files, weapon
bodies, animation banks, textures or editing-kit executables in the output.
"""
import hashlib
import json
import math
from pathlib import Path

from export_reload_sources import ROOT, OUT

TITLES = {"H3EK":"Halo3", "H3ODSTEK":"Halo3ODST", "HREK":"HaloReach",
          "H4EK":"Halo4", "HCEEK":"HaloCE", "H2EK":"Halo2"}


def number(v):
    assert math.isfinite(v)
    text = f"{v:.9g}"
    return text + ("f" if "." in text or "e" in text else ".0f")


def main():
    vertices, records, evidence = [], [], []
    for kit,title in TITLES.items():
        for path in sorted((OUT/"geometry"/kit).glob("*.json")):
            data=json.loads(path.read_text())
            name=Path(data["tag"]).stem if kit!="HCEEK" else Path(data["tag"]).parent.parent.name
            identity=data["checksum"] if kit!="H2EK" else int(hashlib.sha256(data["tag"].encode()).hexdigest()[:16],16)
            assert identity
            bounds=data["bounds"] or [[0,0]]*3
            low=[p[0] for p in bounds];high=[p[1] for p in bounds]
            needles="needler" in name or "needle_rifle" in name
            points=data["vertices"]
            center=[(lo+hi)/2 for lo,hi in zip(data["minimum"],data["maximum"])]
            first=len(vertices)
            for triangle in data["triangles"]:
                positions=[]
                for i in triangle:
                    p=[(points[i][a]-center[a])*3.048 for a in range(3)]
                    positions.append([-p[1],p[2],-p[0]])
                u=[positions[1][a]-positions[0][a] for a in range(3)]
                v=[positions[2][a]-positions[0][a] for a in range(3)]
                normal=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]
                length=math.sqrt(sum(x*x for x in normal))
                if length<1e-10:continue
                normal=[x/length for x in normal]
                for p in positions:
                    assert all(abs(x)<1.0 for x in p), (kit,name,p)
                    vertices.append((p,normal))
            count=len(vertices)-first
            record=(title,identity,name,needles,len(data["nodes"]),first,count,low,high)
            prior=next((r for r in records if r[:2]==record[:2]),None)
            if prior:
                assert prior[3:5]==record[3:5] and vertices[prior[5]:prior[5]+prior[6]]==vertices[first:],(kit,name,"identity collision")
                vertices=vertices[:first]
                continue
            records.append(record)
            evidence.append(dict(title=title,name=name,identity=f"{identity:016X}",source_tag=data["tag"],
                                 source_sha256=data["sha256"],nodes=data["nodes"],selected=data["selected_nodes"],
                                 triangle_count=count//3,needles=needles))
    lines=["// Generated by tools/re/generate_reload_catalog.py. Per-title official model identities.",
           "#pragma once", "namespace weapon_model {", "inline constexpr Model kModels[]{"]
    for title,identity,name,needles,nodes,first,count,low,high in records:
        lines.append('    {GameTitle::%s,0x%016Xull,"%s",%s,%d,%d,%d,{%s},{%s}},'%
                     (title,identity,name,str(needles).lower(),nodes,first,count,','.join(map(number,low)),','.join(map(number,high))))
    lines.extend(["};", "}", ""])
    (ROOT/"src/common/weapon_models.generated.h").write_text('\n'.join(lines))
    lines=["// Generated magazine-only vertices in metres, with mod-provided surface shading.",
           "#pragma once", "namespace weapon_model {", "inline constexpr Vertex kVertices[]{"]
    for point,normal in vertices:
        lines.append('    {{%s},{%s}},'%(','.join(map(number,point)),','.join(map(number,normal))))
    lines.extend(["};", "}", ""])
    (ROOT/"src/common/weapon_magazines.generated.h").write_text('\n'.join(lines))
    (ROOT/"docs/RELOAD-CATALOG-EVIDENCE-2026-09-16.json").write_text(json.dumps(evidence,indent=2)+'\n')
    print(json.dumps(dict(models=len(records),visible_magazines=sum(r[6]>0 for r in records),
                          needle_models=sum(r[3] for r in records),vertices=len(vertices))))


if __name__=="__main__":main()
