"""Generate the CE loaded-image checks from the pinned evidence ledger.

No process access or game-file writes. --check refuses a stale generated header.
The header is tracked so source archives do not require Python to build.
"""
import argparse
import json
from pathlib import Path


def contract_lines(contracts):
    entries, witnesses, relatives, pointers = [], [], [], []
    for item in contracts:
        entries.append(f'    {{"{item["name"]}",{item["rva"]},"{item["signature"]}",'
                       f'{str(item.get("function_entry", False)).lower()}}},')
        for witness in item.get("instruction_witnesses", []):
            witnesses.append(f'    {{{witness["rva"]},"{witness["signature"]}"}},')
        for edge in item.get("relative_operands", []):
            witnesses.append(f'    {{{edge["instruction_rva"]},"{edge["instruction_signature"]}"}},')
            relatives.append(f'    {{{edge["instruction_rva"]},{edge["instruction_bytes"]},'
                             f'{edge["displacement_offset"]},{edge["target_rva"]}}},')
        for pointer in item.get("image_pointers", []):
            pointers.append(f'    {{{pointer["rva"]},{pointer["target_rva"]}}},')
    lines = []
    for kind, name, values in [("Entry", "entries", entries), ("Witness", "witnesses", witnesses),
                               ("Relative", "relatives", relatives), ("Pointer", "pointers", pointers)]:
        lines += [f'inline constexpr std::array<{kind},{len(values)}> {name}={{{{'] + values + ['}};']
    for item in contracts:
        lines.append(f'inline constexpr uint32_t {item["name"]}={item["rva"]};')
    return lines


def generate(manifest):
    contracts = manifest["offline_render_contracts"]
    lines = ["// Generated by tools/re/generate_ce_contracts.py; do not edit.",
             "// Offline identity evidence is not title admission or headset acceptance.",
             "#pragma once", "#include <cstdint>", "#include <array>", "namespace halo_ce::contract {",
             "struct Entry { const char* name; uint32_t rva; const char* pattern; bool unwind; };",
             "struct Witness { uint32_t rva; const char* pattern; };",
             "struct Relative { uint32_t rva, size, displacement, target; };",
             "struct Pointer { uint32_t rva, target; };",
             f'inline constexpr uint32_t imageSize={manifest["retail"]["image_size"]};',
             f'inline constexpr uint32_t timestamp={manifest["retail"]["timestamp"]};']
    groups = {}
    for item in contracts:
        group = item.get("runtime_group", "core")
        if not group.isidentifier():
            raise ValueError(f"Invalid runtime contract group {group!r}")
        groups.setdefault(group, []).append(item)
    lines += contract_lines(groups.pop("core", []))
    for group, items in sorted(groups.items()):
        lines += [f'namespace {group} {{'] + contract_lines(items) + ['}']
    return "\n".join(lines + ["}", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    manifest = json.loads((root / "docs/HALOCE-EVIDENCE-MANIFEST.json").read_text(encoding="utf-8-sig"))
    header = root / "src/common/haloce_contracts.generated.h"
    expected = generate(manifest)
    if args.check:
        if not header.exists() or header.read_text(encoding="utf-8") != expected:
            raise SystemExit("CE loaded-image contract header is stale; regenerate it")
        print("CE loaded-image contracts match the evidence ledger")
    else:
        header.write_text(expected, encoding="utf-8")
