"""Generate the CE loaded-image checks from the pinned evidence ledger.

No process access or game-file writes. --check refuses a stale generated header.
The header is tracked so source archives do not require Python to build.
"""
import argparse
import json
from pathlib import Path


def generate(manifest):
    contracts = manifest["offline_render_contracts"]
    lines = ["// Generated by tools/re/generate_ce_contracts.py; do not edit.",
             "// Offline identity evidence is not title admission or headset acceptance.",
             "#pragma once", "#include <cstdint>", "namespace halo_ce::contract {",
             "struct Entry { const char* name; uint32_t rva; const char* pattern; bool unwind; };",
             "struct Witness { uint32_t rva; const char* pattern; };",
             "struct Relative { uint32_t rva, size, displacement, target; };",
             "struct Pointer { uint32_t rva, target; };",
             f'inline constexpr uint32_t imageSize={manifest["retail"]["image_size"]};',
             f'inline constexpr uint32_t timestamp={manifest["retail"]["timestamp"]};',
             "inline constexpr Entry entries[]={"]
    for item in contracts:
        lines.append(f'    {{"{item["name"]}",{item["rva"]},"{item["signature"]}",'
                     f'{str(item.get("function_entry", False)).lower()}}},')
    lines += ["};", "inline constexpr Witness witnesses[]={"]
    for item in contracts:
        for witness in item.get("instruction_witnesses", []):
            lines.append(f'    {{{witness["rva"]},"{witness["signature"]}"}},')
        for edge in item.get("relative_operands", []):
            lines.append(f'    {{{edge["instruction_rva"]},"{edge["instruction_signature"]}"}},')
    lines += ["};", "inline constexpr Relative relatives[]={"]
    for item in contracts:
        for edge in item.get("relative_operands", []):
            lines.append(f'    {{{edge["instruction_rva"]},{edge["instruction_bytes"]},'
                         f'{edge["displacement_offset"]},{edge["target_rva"]}}},')
    lines += ["};", "inline constexpr Pointer pointers[]={"]
    for item in contracts:
        for pointer in item.get("image_pointers", []):
            lines.append(f'    {{{pointer["rva"]},{pointer["target_rva"]}}},')
    lines += ["};"]
    for item in contracts:
        lines.append(f'inline constexpr uint32_t {item["name"]}={item["rva"]};')
    return "\n".join(lines + ["}", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    manifest = json.loads((root / "docs/HALOCE-EVIDENCE-MANIFEST.json").read_text(encoding="utf-8-sig"))
    header = root / "src/common/haloce_contracts.generated.h"
    expected = generate(manifest)
    if args.check:
        if not header.exists() or header.read_text(encoding="utf-8") != expected:
            raise SystemExit("CE loaded-image contract header is stale; regenerate it")
        print("CE loaded-image contracts match the evidence ledger")
    else:
        header.write_text(expected, encoding="utf-8")
