"""Reproduce verified native reload-tail bindings; not a discovery scanner.

See docs/NATIVE-RELOAD-TAIL-2026-09-18.md for per-engine evidence.
"""
from pathlib import Path
import hashlib,json,sys
sys.path.insert(0,'out/pydeps')
import pefile
from capstone import Cs,CS_ARCH_X86,CS_MODE_64
rows=[
 ('halo1.dll',[0xa9b648,0,0],0xb285a8,0xb773e0,[0x2d9cd90,0x2d9ce10,0x2ea3410]),
 ('halo2.dll',[0x7a0730,0x79df70,0x7a0d60],0x81a2e0,0,[0x187c300,0,0]),
 ('halo3.dll',[0x15d174,0x231968,0x26b1a0],0,0,[0,0,0]),
 ('halo3odst.dll',[0x18b158,0x26062c,0x296ff8],0,0,[0,0,0]),
 ('haloreach.dll',[0x211310,0x217d38,0x20ef14],0,0,[0,0,0]),
 ('halo4.dll',[0x2f9028,0x2ef5a4,0x2f9a00],0,0,[0,0,0]),
]
output=['// Generated by tools/re/generate_reload_tail_bindings.py.',
        'static constexpr TailBindingSet kTailBindings[]{']
ledger=[]
for module,functions,play,duration,globals_ in rows:
 path=Path('out/deps/re-tools/inputs')/module
 pe=pefile.PE(str(path));im=pe.get_memory_mapped_image();md=Cs(CS_ARCH_X86,CS_MODE_64);md.detail=True
 proofs=[]
 length={'haloreach.dll':0x210da8,'halo4.dll':0x2f94a4}.get(module,0)
 for n,target in enumerate(globals_):
  if not target:proofs.append(0);continue
  start=play if n==0 else duration
  hit=next((i.address for i in md.disasm(im[start:start+0x900],start)
            if any(o.type==3 and i.reg_name(o.mem.base)=='rip' and i.address+i.size+o.mem.disp==target for o in i.operands)),None)
  assert hit is not None,(module,hex(target))
  proofs.append(hit)
 def binding(rva):
  if not rva:return '{0,nullptr}'
  for n in range(32,97,8):
   b=im[rva:rva+n]
   if im.count(b)==1:return '{0x%x,"%s"}'%(rva,b.hex(' ').upper())
  raise RuntimeError((module,rva,'not unique'))
 output.append('    {{{'+', '.join(binding(v) for v in functions+proofs+[length])+'}}, {'+', '.join('0x%x'%v for v in globals_)+'}},')
 ledger.append(dict(module=module,sha256=hashlib.sha256(path.read_bytes()).hexdigest(),functions=[hex(v) for v in functions],global_proofs=[hex(v) for v in proofs],globals=[hex(v) for v in globals_],length_function=hex(length)))
output.append('};')
for path,content in [(Path('src/dll/native_reload_tail_bindings.generated.h'),'\n'.join(output)+'\n'),
                     (Path('docs/NATIVE-RELOAD-TAIL-BINDINGS-2026-09-18.json'),json.dumps(ledger,indent=2)+'\n')]:
 if '--check' in sys.argv:assert path.read_text(encoding='utf-8')==content,path
 else:path.write_text(content,encoding='utf-8')
print('Verified reload-tail bindings for',len(rows),'titles')
