"""Reproduce cold signatures from pinned inputs, never discover bindings.

Function identities and title-specific behavior are recorded in
docs/NATIVE-RELOAD-POLICY-2026-09-16.md. Outputs contain code signatures only.
"""
from pathlib import Path
import hashlib,json,sys
sys.path.insert(0,str(Path('out/pydeps')))
import pefile

# auto request, magazine state/start, action dispatch, first-person play/check,
# animation duration, auto-only call instruction (not its return address).
rows=[
 ('HaloCE','halo1.dll',[0xb7814c,0,0xb27ba0,0xb285a8,0xb773e0],0xb759e5),
 ('Halo2','halo2.dll',[0x8eadf0,0x8e9ed0,0x819d50,0x81a2e0,0x81c750],0x8e472a),
 ('Halo3','halo3.dll',[0x35f040,0x36a394,0x2c1e60,0x2c2474,0x2c1cac],0x36588d),
 ('Halo3ODST','halo3odst.dll',[0x3a5208,0x3b0d08,0x2ea3fc,0x2eaa10,0x2ea21c],0x3abc11),
 ('HaloReach','haloreach.dll',[0x4b6868,0x4c529c,0x2b0fe8,0x2b1910,0x2b0dc4],0x4bedf6),
 ('Halo4','halo4.dll',[0x607e08,0x61a904,0x3b399c,0x3b439c,0x3b374c],0x6131f5),
]
result=['// Generated by tools/re/generate_reload_policy_bindings.py.','static constexpr BindingSet kBindings[]{']
ledger=[]
for title,module,entries,call in rows:
 path=Path('out/deps/re-tools/inputs')/module
 pe=pefile.PE(str(path),fast_load=True);im=pe.get_memory_mapped_image()
 # Verify the already established direct edge; never search for a replacement.
 assert im[call]==0xe8 and call+5+int.from_bytes(im[call+1:call+5],'little',signed=True)==entries[0],title
 def pattern(rva):
  if not rva:return 'nullptr'
  for n in range(32,97,8):
   data=im[rva:rva+n]
   if im.count(data)==1: return '"'+data.hex(' ').upper()+'"'
  raise RuntimeError((title,hex(rva),'not unique'))
 result.append('    {GameTitle::'+title+', {{'+', '.join('{0x%x,%s}'%(a,pattern(a)) for a in entries)+'}}, {0x%x,%s}, 0x%x},'%(call-16,pattern(call-16),call+5))
 ledger.append(dict(title=title,module=module,sha256=hashlib.sha256(path.read_bytes()).hexdigest(),entries=[hex(x) for x in entries],auto_call=hex(call)))
result.append('};')
for path,content in [(Path('src/dll/native_reload_bindings.generated.h'),'\n'.join(result)+'\n'),
                     (Path('docs/NATIVE-RELOAD-BINDINGS-2026-09-16.json'),json.dumps(ledger,indent=2)+'\n')]:
 if '--check' in sys.argv:
  assert path.read_text()==content,f'{path}: generated binding differs'
 else: path.write_text(content)
print(json.dumps(ledger,indent=2))
