"""Generate bounded magazine-only VR geometry and per-title identity metadata.

Consumes verified isolated geometry; never includes original tag files, weapon
bodies, animation banks or editing-kit executables in the output. Texture output
is cropped to the isolated assemblies' UV regions.
"""
import hashlib
import json
import math
from pathlib import Path

from export_reload_sources import ROOT, OUT
from reload_surface_atlas import Atlas
from reload_tag_xml import read,block,value
from verify_ce_weapon_mesh import read_weapon,derive
from verify_ce_first_person_tags import inspect
from verify_ce_floating_hand_mesh import inverse,point,add,mul,cross,dot

TITLES = {"H3EK":"Halo3", "H3ODSTEK":"Halo3ODST", "HREK":"HaloReach",
          "H4EK":"Halo4", "HCEEK":"HaloCE", "H2EK":"Halo2"}


def number(v):
    assert math.isfinite(v)
    text = f"{v:.9g}"
    return text + ("f" if "." in text or "e" in text else ".0f")


def receiver_anchor(kit,data,center):
    if not data["triangles"]:return [0,0,0]
    if kit=="HCEEK":
        path=ROOT/data["tag"]
        _,names,_,rest,_,_=read_weapon(path)
        record,fixture=inspect(path.with_suffix(".model_animations"))
        graph=[fixture[i:i+32].split(b"\0",1)[0].decode() for i in range(4,len(fixture),64)]
        carrier=rest[names.index(graph[record["weapon_root"]])]
    else:
        node=block(read(ROOT/data["xml"]),"nodes")[0]
        # Native XML inverse_* labels are displaced by the packed matrix's
        # leading scale. Derive from the independently named default pose.
        parent=value(node,"parent node","")
        if not parent:
            parent=next(x for x in node if x.tag=="block_index" and x.get("type")=="parent node").get("index")
        assert parent in ("NONE",",-1","-1"),(kit,data["tag"],parent)
        translation=[float(x) for x in value(node,"default translation").split(",")]
        q=[float(x) for x in value(node,"default rotation").split(",")]
        assert abs(dot(q,q)-1)<.00001
        basis=[]
        for axis in ((1,0,0),(0,1,0),(0,0,1)):
            t=mul(cross(q[:3],axis),2)
            basis.extend(add(add(axis,mul(t,q[3])),cross(q[:3],t)))
        carrier=(1,*basis,*translation)
    local=inverse(carrier,center)
    assert all(abs(a-b)<1e-6 for a,b in zip(point(carrier,local),center))
    assert all(math.isfinite(x) and abs(x)<1 for x in local)
    return local


def main():
    vertices, records, evidence = [], [], []
    atlas=Atlas()
    for kit,title in TITLES.items():
        for path in sorted((OUT/"geometry"/kit).glob("*.json")):
            data=json.loads(path.read_text())
            name=Path(data["tag"]).stem if kit!="HCEEK" else Path(data["tag"]).parent.parent.name
            identity=data["checksum"] if kit!="H2EK" else int(hashlib.sha256(data["tag"].encode()).hexdigest()[:16],16)
            assert identity
            bounds=data["bounds"] or [[0,0]]*3
            low=[p[0] for p in bounds];high=[p[1] for p in bounds]
            needles="needler" in name or "needle_rifle" in name
            points=data["vertices"]
            center=[(lo+hi)/2 for lo,hi in zip(data["minimum"],data["maximum"])]
            first=len(vertices)
            triangle_uvs=atlas.add(kit,data)
            for triangle_index,triangle in enumerate(data["triangles"]):
                positions=[]
                for i in triangle:
                    p=[(points[i][a]-center[a])*3.048 for a in range(3)]
                    positions.append([-p[1],p[2],-p[0]])
                u=[positions[1][a]-positions[0][a] for a in range(3)]
                v=[positions[2][a]-positions[0][a] for a in range(3)]
                normal=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]
                length=math.sqrt(sum(x*x for x in normal))
                if length<1e-10:continue
                normal=[x/length for x in normal]
                for p,uv in zip(positions,triangle_uvs[triangle_index]):
                    assert all(abs(x)<1.0 for x in p), (kit,name,p)
                    vertices.append((p,normal,uv))
            count=len(vertices)-first
            anchor=receiver_anchor(kit,data,center)
            record=(title,identity,name,needles,len(data["nodes"]),first,count,low,high,anchor)
            prior=next((r for r in records if r[:2]==record[:2]),None)
            if prior:
                assert prior[3:5]==record[3:5] and vertices[prior[5]:prior[5]+prior[6]]==vertices[first:],(kit,name,"identity collision")
                vertices=vertices[:first]
                continue
            records.append(record)
            evidence.append(dict(title=title,name=name,identity=f"{identity:016X}",source_tag=data["tag"],
                                 source_sha256=data["sha256"],nodes=data["nodes"],selected=data["selected_nodes"],
                                 triangle_count=count//3,needles=needles,receiver_anchor=anchor))
    lines=["// Generated by tools/re/generate_reload_catalog.py. Per-title official model identities.",
           "#pragma once", "namespace weapon_model {", "inline constexpr Model kModels[]{"]
    for title,identity,name,needles,nodes,first,count,low,high,anchor in records:
        lines.append('    {GameTitle::%s,0x%016Xull,"%s",%s,%d,%d,%d,{%s},{%s},{%s}},'%
                     (title,identity,name,str(needles).lower(),nodes,first,count,','.join(map(number,low)),','.join(map(number,high)),','.join(map(number,anchor))))
    lines.extend(["};", "}", ""])
    (ROOT/"src/common/weapon_models.generated.h").write_text('\n'.join(lines))
    atlas_width,atlas_height=atlas.finish()
    lines=["// Generated magazine-only vertices in metres with authored surface UVs.",
           "#pragma once", "namespace weapon_model {", "inline constexpr Vertex kVertices[]{"]
    for point,normal,uv in vertices:
        lines.append('    {{%s},{%s},{%s}},'%(','.join(map(number,point)),','.join(map(number,normal)),
            ','.join(map(number,(uv[0]/atlas_width,uv[1]/atlas_height)))))
    lines.extend(["};", "}", ""])
    (ROOT/"src/common/weapon_magazines.generated.h").write_text('\n'.join(lines))
    (ROOT/"docs/RELOAD-CATALOG-EVIDENCE-2026-09-16.json").write_text(json.dumps(evidence,indent=2)+'\n')
    print(json.dumps(dict(models=len(records),visible_magazines=sum(r[6]>0 for r in records),
                          needle_models=sum(r[3] for r in records),vertices=len(vertices))))


if __name__=="__main__":main()
