"""Derive CE's bilateral hand and weapon-local reflection planes from HCEEK."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import struct
import subprocess
import tempfile

from verify_ce_floating_hand_mesh import inspect_official_kit, read_mesh, inverse, point, direction, add
from verify_ce_weapon_mesh import derive, read_weapon, inspect_extra_descriptors
from verify_ce_first_person_tags import inspect

ROOT = Path(__file__).resolve().parents[2]


def records():
    inspect_official_kit(ROOT / "out/deps/re-tools/inputs/halo_tag_test.exe")
    inspect_extra_descriptors()
    path = ROOT / "out/ce-hands-hceek-tags/tags/characters/cyborg/fp/fp.gbxmodel"
    data, names, parents, rest, _, _ = read_mesh(path)
    left, right = names.index("frame l wriste"), names.index("frame r wriste")
    assert rest[left][1:10] == rest[right][1:10] == (1., 0., 0., 0., 1., 0., 0., 0., 1.)
    landmarks = []
    for node, parent in enumerate(parents):
        if parent != left:
            continue
        opposite_name = names[node].replace("frame l ", "frame r ", 1)
        if opposite_name == "frame r middlelow":
            opposite_name = "frame r middle low"  # Different official spelling.
        opposite = names.index(opposite_name)
        assert parents[opposite] == right
        a = inverse(rest[left], rest[node][10:13])
        b = inverse(rest[right], rest[opposite][10:13])
        error = max(abs(a[i] - b[i] * (1, -1, 1)[i]) for i in range(3))
        assert error < .00004
        landmarks.append(dict(left=names[node], right=names[opposite],
                              left_position=a, right_position=b, mirror_residual=error))
    assert len(landmarks) == 5
    result = []
    for path in sorted((ROOT / "out/ce-hands-hceek-tags/tags/weapons").glob("*/fp/*.gbxmodel")):
        record = derive(path)  # Checks complete graph identity and model-node/parent mapping.
        _, model_names, _, matrices, _, _ = read_weapon(path)
        matrix = matrices[model_names.index(record["weapon_root_name"])]
        # Model lateral Y=0 expressed in weapon-root coordinates. The roots of
        # Oddball, Needler and plasma cannon are not all model-axis aligned.
        raw = (matrix[2], matrix[5], matrix[8])
        length = math.sqrt(sum(x*x for x in raw))
        assert abs(length-1) < .00001
        normal = tuple(x/length for x in raw)
        offset = matrix[11]/matrix[0]/length
        result.append(dict(name=path.parent.parent.name, graph_identity=record["graph_identity"],
                           nodes=record["nodes"], gun_node=record["weapon_root"],
                           model=record["model_file"], model_sha256=record["model_sha256"],
                           root_matrix=matrix, normal=normal, offset=offset))
    assert len(result) == 12 and len({r["graph_identity"] for r in result}) == 12
    return dict(hand_model_sha256=hashlib.sha256(data).hexdigest().upper(),
                landmarks=landmarks, weapons=result)


def header(report):
    def number(x):
        value = f"{x:.9g}"
        return value + ("f" if "." in value or "e" in value else ".0f")
    output = ["// Generated by tools/re/verify_ce_hand_alignment.py from official HCEEK tags.",
              "// Model-lateral reflection plane in each verified weapon-root frame.",
              "#pragma once", "namespace halo_ce", "{",
              "struct HandAlignmentPlane", "{",
              "    uint64_t graphIdentity{};uint16_t graphCount{},gunNode{};",
              "    Vec3 normal{};float offset{};", "};",
              "inline constexpr HandAlignmentPlane kCeHandAlignmentPlanes[]{"]
    for r in report["weapons"]:
        output.append(f'    {{0x{r["graph_identity"]}ull,{r["nodes"]},{r["gun_node"]},'
                      f'{{{",".join(map(number,r["normal"]))}}},{number(r["offset"])}}}, // {r["name"]}')
    return "\n".join(output + ["};", "}", ""])


def exercise_adapter(report, adapter):
    _, hand_names, _, hand_rest, _, _ = read_mesh(
        ROOT / "out/ce-hands-hceek-tags/tags/characters/cyborg/fp/fp.gbxmodel")
    # Use actual official graph/model mappings and independent Python affine
    # math to check the compiled production palette, rather than a parallel
    # reimplementation of its wrist routing.
    pose_carrier = (1.3, math.cos(.41), math.sin(.41), 0,
                    -math.sin(.41), math.cos(.41), 0, 0, 0, 1, 100, 200, 300)
    cases = 0
    with tempfile.TemporaryDirectory(prefix="ce-hand-alignment-", dir=ROOT / "out") as scratch:
        before, after = Path(scratch) / "input.bin", Path(scratch) / "output.bin"
        for record in report["weapons"]:
            path = ROOT / record["model"]
            graph, fixture = inspect(path.with_suffix(".model_animations"))
            count = graph["nodes"]
            names = [fixture[4+i*64:4+i*64+32].split(b"\0", 1)[0].decode() for i in range(count)]
            _, model_names, _, rest, _, _ = read_weapon(path)
            source = []
            for name in names:
                if name in model_names:
                    matrix = rest[model_names.index(name)]
                elif name in hand_names:
                    matrix = hand_rest[hand_names.index(name)]
                else:
                    matrix = hand_rest[hand_names.index("frame r wriste")]
                basis = tuple(v for i in range(3) for v in direction(pose_carrier, matrix[1+i*3:4+i*3]))
                source.append((matrix[0]*pose_carrier[0], *basis, *point(pose_carrier, matrix[10:13])))
            gun = record["gun_node"]
            left, right = graph["left_wrist"], graph["right_wrist"]
            authored = b"".join(struct.pack("<13f", *m) for m in source)

            def invoke(flags, scale):
                before.write_bytes(fixture + authored + struct.pack("<Iff", flags, scale, 1.1))
                result = subprocess.run([str(adapter), "--floating-mesh-fixture", str(before), str(after)],
                                        capture_output=True, text=True)
                assert result.returncode == 0, (record["name"], flags, scale, result.stdout, result.stderr)
                raw = after.read_bytes()
                assert len(raw) == count*52
                return [struct.unpack_from("<13f", raw, i*52) for i in range(count)]

            def expected(wrist, rendered_gun):
                carrier = source[gun]
                local_position = inverse(carrier, wrist[10:13])
                normal, offset = record["normal"], record["offset"]
                distance = sum(a*b for a, b in zip(normal, local_position))+offset
                position = tuple(a-2*distance*b for a, b in zip(local_position, normal))
                basis = []
                for column in range(3):
                    axis = wrist[1+column*3:4+column*3]
                    local = tuple(sum(carrier[1+i*3+j]*axis[j] for j in range(3)) for i in range(3))
                    distance = sum(a*b for a, b in zip(normal, local))
                    reflected = tuple((a-2*distance*b)*(-1 if column == 1 else 1) for a, b in zip(local, normal))
                    basis.extend(direction(rendered_gun, reflected))
                return (wrist[0]*rendered_gun[0]/carrier[0], *basis, *point(rendered_gun, position))

            for scale in (.3, .75, 3.):
                baseline = invoke(2, scale)
                aligned = invoke(6, scale)
                assert baseline[gun] == aligned[gun], (record["name"], "gun changed")
                for node in (left,):
                    target = expected(source[right], aligned[gun])
                    assert max(abs(a-b) for a, b in zip(aligned[node], target)) < .00015, (record["name"], "primary", aligned[node], target)
                planted = invoke(14, scale)
                assert planted[gun] == baseline[gun], (record["name"], "planted gun changed")
                target = expected(source[left], planted[gun])
                assert max(abs(a-b) for a, b in zip(planted[right], target)) < .00015, (record["name"], "support", planted[right], target)
                assert invoke(0, scale) == invoke(4, scale), (record["name"], "right-handed changed")
                cases += 1
    return dict(compiled_stock_cases=cases, compiled_palettes=cases*5,
                adapter_sha256=hashlib.sha256(adapter.read_bytes()).hexdigest().upper(),
                checks="12 official graphs, tilted/scaled authored poses, 3 mount scales, primary and planted support, unchanged weapon and right-handed palette",
                limit="Local primary-asset/compiled-transform checks; no live game or headset.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--record", type=Path)
    parser.add_argument("--adapter-exe", type=Path)
    args = parser.parse_args()
    report = records()
    generated = header(report)
    target = ROOT / "src/common/haloce_hand_alignment.generated.h"
    if args.write:
        target.write_text(generated)
    else:
        assert target.read_text() == generated, "Generated CE alignment planes are stale"
    if args.adapter_exe:
        report.update(exercise_adapter(report, args.adapter_exe.resolve()))
    if args.record:
        args.record.write_text(json.dumps(report, indent=2)+"\n")
    print(json.dumps(dict(weapons=len(report["weapons"]), bilateral_landmarks=len(report["landmarks"]),
                         generated=str(target))))


if __name__ == "__main__":
    main()
